[application]
name = "NoSave Chat"

[bundle]
identifier = "com.swarnim.nosavechat"
publisher = "Swarnim"
icon = ["assets/icon.png"]

[web.app]

# HTML title tag content
title = "NoSave Chat"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
